Specifying Path to Composite Entity Patterns File in Config.yml
BeWe11/rasa_composite_entities pull request #13
Opened 2019-12-31 15:44 UTC by ttlekich

Related to #9. 

I added a section in the readme explaining how to use this new configuration option - let me know if there are any questions. I tested this with relative and absolute paths to the training file. If one were to run `rasa train` in the rasa directory, a relative path is fine, however invoking `rasa train` from another location requires the composite entity patterns path to be absolute. 

I was not able to test out the existing cmd line or http routes of loading the composite entity file. If someone with this setup can test this, I would be grateful. If not, I can try to set something up in the next day or two. 

I'm happy to make any further changes!

(Also, this might be minor and I do not think I included it in this PR: I found that using a `value` field that is the same as the `contained_entities` field works nicer if passing the nlu object to a typed language because as far as I've found all other entity objects have a `value` field).

2020-01-02 11:08 UTC, BeWe11 requested changes
Thank you for this PR! I've made a few small suggestions, please take a look.

Also, can you test the "cmd line" route of fetching the patterns? You can just use the example files in this repo or copy-paste you definitions into the training file.

By the way, I'm not sure I understand you bracketed comment about the `value` fields. Can you expand what you mean?

2020-01-02 11:08 UTC, BeWe11 commented on rasa_composite_entities/composite_entity_extractor.py
> +from rasa.nlu.training_data.loading import _guess_format, guess_format
Why did you load another `guess_format` method here? It's not used anywhere.

2020-01-02 11:08 UTC, BeWe11 commented on rasa_composite_entities/composite_entity_extractor.py
> +                composite_entities_file, self.composite_entities, separators=(",", ": ")
Are you using an autoformatter? I'd prefer if you'd let formatting intact in places where you didn't perform any changes (same for the changes below).

2020-01-02 11:08 UTC, BeWe11 commented on rasa_composite_entities/composite_entity_extractor.py
> +COMPOSITE_PATTERNS_KEY = "composite_entity_patterns"
The key should contain the word `path` in it. I would probably use `composite_patterns_path`.

2020-01-02 11:08 UTC, BeWe11 commented on README.md
> +  composite_entity_patterns: "path/to/composite_entity_patterns.json"
See comment below about the `COMPOSITE_PATTERNS_KEY`.

2020-01-02 11:08 UTC, BeWe11 commented on README.md
>  ## Usage
I would prefer if the explanation about the optional path parameter would be placed into the "Usage" section. Also, you should clarify that either option works, but that giving a path to an external composite patterns file is the preferred option.

2020-01-02 14:16 UTC, ttlekich commented
Thank you for the review! I'll try to get those changes in soon. 

Regarding `value`, this is probably out of the scope of this PR and more so a preference for me, so I did not include it in the code (and probably should have just opened another conversation). Though to explain, most other extractors give an entity object structure like:

2020-01-03 10:12 UTC, BeWe11 commented
Ah, I get what you mean now. In hindsight, it seems to be an obvious choice to reuse the `value` key instead of introducing a new `contained_entities` key.

In the same manner, it might be a good idea to idea to assign a `start` and `end` to the composite entities as well, so that all common entity keys are populated.

I'm gonna add these keys to the result dict and rename `contained_entities` to `value`. When your pull request is merged, I'm gonna release a new major version, so that this breaking change can be anticipated (the new mode of loading the pattern file warrants a major version bump as well, I guess).

2020-01-03 10:13 UTC, BeWe11 commented on rasa_composite_entities/composite_entity_extractor.py
> +from rasa.nlu.training_data.loading import _guess_format, guess_format
I now see that `_guess_format` is deprecated and `guess_format` is preferred. While you are at it, can you remove the `_guess_format` import and use `guess_format` in its place?

2020-01-08 21:25 UTC, ttlekich commented on rasa_composite_entities/composite_entity_extractor.py
> +from rasa.nlu.training_data.loading import _guess_format, guess_format
Yep! Will replace it - not sure if it was there because of backwards compatibility with older rasa versions.

2020-01-08 21:25 UTC, ttlekich commented on rasa_composite_entities/composite_entity_extractor.py
> +                composite_entities_file, self.composite_entities, separators=(",", ": ")
Yeah, sorry! I forget to turn it off somethings...

2020-01-08 21:26 UTC, ttlekich commented
Will hopefully have the fixes in tomorrow morning. I apologize that I've been so slow - work has been super busy.

2020-01-09 14:11 UTC, ttlekich commented
Hopefully updated the requests you made. Here is a summary of the testing I did:
## Manual Testing 

### Installation:

```bash
cd example
pyenv local 3.6.8
python -m venv env
source env/bin/activate
pip install --upgrade pip
pip install rasa spacy
pip install git+https://github.com/ttlekich/rasa_composite_entities.git
python -m spacy download en_core_web_md
python -m spacy link en_core_web_md en
```

### Train without composite:

Input:
```
rasa train nlu --out . --nlu train.json --config config_without_composite.yml
rasa run --enable-api --model .
```

Output:
```
{
  "intent": { "name": "product_search", "confidence": 0.7862067786 },
  "entities": [
    {
      "start": 19,
      "end": 22,
      "value": "red",
      "entity": "color",
      "confidence": 0.9029129134,
      "extractor": "CRFEntityExtractor"
    },
    {
      "start": 23,
      "end": 28,
      "value": "shirt",
      "entity": "product",
      "confidence": 0.9006936405,
      "extractor": "CRFEntityExtractor"
    },
    {
      "start": 34,
      "end": 41,
      "value": "stripes",
      "entity": "pattern",
      "confidence": 0.8653145606,
      "extractor": "CRFEntityExtractor"
    },
    {
      "start": 46,
      "end": 55,
      "value": "checkered",
      "entity": "pattern",
      "confidence": 0.8578084474,
      "extractor": "CRFEntityExtractor"
    },
    {
      "start": 56,
      "end": 60,
      "value": "blue",
      "entity": "color",
      "confidence": 0.8547734472,
      "extractor": "CRFEntityExtractor"
    },
    {
      "start": 61,
      "end": 66,
      "value": "shoes",
      "entity": "product",
      "confidence": 0.8340521862,
      "extractor": "CRFEntityExtractor"
    }
  ],
  "intent_ranking": [
    { "name": "product_search", "confidence": 0.7862067786 },
    { "name": "greet", "confidence": 0.2137932214 }
  ],
  "text": "I am looking for a red shirt with stripes and checkered blue shoes"
}

```

### Train composite (definied by cli):

Input:
```
rasa train nlu --out . --nlu train.json --config config_with_composite.yml
rasa run --enable-api --model .
```

Output:
```
{
  "intent": { "name": "product_search", "confidence": 0.7786392795 },
  "entities": [
    {
      "confidence": 1.0,
      "entity": "product_with_attributes",
      "extractor": "composite",
      "contained_entities": [
        {
          "start": 19,
          "end": 22,
          "value": "red",
          "entity": "color",
          "confidence": 0.9029129134,
          "extractor": "CRFEntityExtractor"
        },
        {
          "start": 23,
          "end": 28,
          "value": "shirt",
          "entity": "product",
          "confidence": 0.9006936405,
          "extractor": "CRFEntityExtractor"
        },
        {
          "start": 34,
          "end": 41,
          "value": "stripes",
          "entity": "pattern",
          "confidence": 0.8653145606,
          "extractor": "CRFEntityExtractor"
        }
      ]
    },
    {
      "confidence": 1.0,
      "entity": "product_with_attributes",
      "extractor": "composite",
      "contained_entities": [
        {
          "start": 46,
          "end": 55,
          "value": "checkered",
          "entity": "pattern",
          "confidence": 0.8578084474,
          "extractor": "CRFEntityExtractor"
        },
        {
          "start": 56,
          "end": 60,
          "value": "blue",
          "entity": "color",
          "confidence": 0.8547734472,
          "extractor": "CRFEntityExtractor"
        },
        {
          "start": 61,
          "end": 66,
          "value": "shoes",
          "entity": "product",
          "confidence": 0.8340521862,
          "extractor": "CRFEntityExtractor"
        }
      ]
    }
  ],
  "intent_ranking": [
    { "name": "product_search", "confidence": 0.7786392795 },
    { "name": "greet", "confidence": 0.2213607205 }
  ],
  "text": "I am looking for a red shirt with stripes and checkered blue shoes"
}
```

### Train composite (definied in config.yml):

Input:
```
rasa train nlu --out . --nlu train.json --config config_with_composite.yml
rasa run --enable-api --model .
```

Output:
```
{
  "intent": { "name": "product_search", "confidence": 0.7775410505 },
  "entities": [
    {
      "confidence": 1.0,
      "entity": "product_with_attributes",
      "extractor": "composite",
      "contained_entities": [
        {
          "start": 19,
          "end": 22,
          "value": "red",
          "entity": "color",
          "confidence": 0.9029129134,
          "extractor": "CRFEntityExtractor"
        },
        {
          "start": 23,
          "end": 28,
          "value": "shirt",
          "entity": "product",
          "confidence": 0.9006936405,
          "extractor": "CRFEntityExtractor"
        },
        {
          "start": 34,
          "end": 41,
          "value": "stripes",
          "entity": "pattern",
          "confidence": 0.8653145606,
          "extractor": "CRFEntityExtractor"
        }
      ]
    },
    {
      "confidence": 1.0,
      "entity": "product_with_attributes",
      "extractor": "composite",
      "contained_entities": [
        {
          "start": 46,
          "end": 55,
          "value": "checkered",
          "entity": "pattern",
          "confidence": 0.8578084474,
          "extractor": "CRFEntityExtractor"
        },
        {
          "start": 56,
          "end": 60,
          "value": "blue",
          "entity": "color",
          "confidence": 0.8547734472,
          "extractor": "CRFEntityExtractor"
        },
        {
          "start": 61,
          "end": 66,
          "value": "shoes",
          "entity": "product",
          "confidence": 0.8340521862,
          "extractor": "CRFEntityExtractor"
        }
      ]
    }
  ],
  "intent_ranking": [
    { "name": "product_search", "confidence": 0.7775410505 },
    { "name": "greet", "confidence": 0.2224589495 }
  ],
  "text": "I am looking for a red shirt with stripes and checkered blue shoes"
}
```

2020-01-10 12:22 UTC, BeWe11 approved these changes

2020-01-10 12:22 UTC, merged

2020-01-10 12:52 UTC, BeWe11 commented
Looks good. I've merged this and changed the Readme to clarify that there are two different modes right at the top. Thank you @ttlekich !

2020-01-10 13:07 UTC, BeWe11 commented
Your pull request is contained in version 0.5.0. As I've mentioned, I have also released version 1.0.0 that renames "contained_entities" to "value" to be consistent with other entity extractors.